### PR TITLE
Responsive rervices features

### LINKED ISSUE #12: 4.1 Responsive services and features sections
## 4.1 Responsive Services and Features

__As as a webdeveloper and member team, I want to set a well good enough layout and responsive for the Services & Features sections .__
> assigned to Eltayeb

### Repo

- [ ] Create  a branch called responsive-services-features. to achieve this user story.

### HTML

- [ ] No HTML added .

### CSS

- [ ] Add media query for services and features sections.

### PR DESCRIPTION
**Pull request by Eltayeb-Elgaali**
i add media queries to services and features sections .
please review and let me know if i should make changes
closes #12

### CODE REVIEW

**Review by yaredyilma — COMMENTED** [review]
Good job El-tayeb! I see you have decided to get rid of the div's which where clustered in one container as we analysed the main website of duck-duck-go on Monday. can you explain why you wanted to place the service features as a column rather than containing them in div's row? The other thing that I have noticed is that, the arrangement of your paragraphs. you have not used any breaks in between so the text is all in one line. you did great with the links.  The rest looks great to me.

**Review by yaredyilma — COMMENTED** [review]
Good job El-tayeb! I see you have decided to get rid of the div's which where clustered in one container as we analysed the main website of duck-duck-go on Monday. can you explain why you wanted to place the service features as a column rather than containing them in div's row? The other thing that I have noticed is that, the arrangement of your paragraphs. you have not used any breaks in between so the text is all in one line. you did great with the links.  The rest looks great to me.

**Review by yildiraykoyuncu — APPROVED** [review]
Nicely done!

**Comment by Eltayeb-Elgaali** [comment]
yes i got what you mean .
i will do that in a new created branch for more separation of work.
thanx for the remarks

**Pull request merged**
